Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,7 +53,11 @@ jobs:
       - name: Run ldd on Tidentification
         run: |
           echo "Running ldd on testBin/Identification/Tidentification..."
-          ldd /home/runner/work/simcoon/simcoon/testBin/Identification/Tidentification || echo "ldd failed!"
+          ldd /usr/share/miniconda3/envs/foo/lib/libarmadillo.so.14 || echo "ldd failed!"
+          ldd /usr/share/miniconda3/envs/foo/lib/./libarpack.so.2 || echo "ldd failed!"
+          ldd /usr/share/miniconda3/envs/foo/lib/././libblas.so.3 || echo "ldd failed!"
+libblas.so.3
+libarpack.so.2
 
       - name: Tests
         shell: bash -l {0}
