Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,10 +53,10 @@ jobs:
       - name: Run ldd on Tidentification
         run: |
           echo "Running ldd on testBin/Identification/Tidentification..."
-          ldd /usr/share/miniconda3/envs/foo/lib/libarmadillo.so.14 || echo "ldd failed!"
+#          ldd /usr/share/miniconda3/envs/foo/lib/libarmadillo.so.14 || echo "ldd failed!"
           ldd /usr/share/miniconda3/envs/foo/lib/./libarpack.so.2 || echo "ldd failed!"
-          ldd /usr/share/miniconda3/envs/foo/lib/././libblas.so.3 || echo "ldd failed!"
-          
+#          ldd /usr/share/miniconda3/envs/foo/lib/././libblas.so.3 || echo "ldd failed!"
+
       - name: Tests
         shell: bash -l {0}
         run: ctest --test-dir ${{github.workspace}}/build
